### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by marcosgerene** [AOPack/SPEDBr.NET#26]
Bom dia @samuelrochaoliveira 

Seria interessante disponibilizar o projeto no nuget, levando em consideração que o projeto não tem dependências externas acredito seja bem prático de fazer e facilite o uso de novos usuários.

Abraços

**Comment by samuelrochaoliveira** [comment]
Bom dia @marcosgerene, já tem um tempo que estou querendo fazer isso para todos os projetos. No caso do SPED queria ter ele mais completo para publicar o pacote mas, nada que nos impeça de fazê-lo agora. Sobre dependências externas... ainda não defini exatamente como vou fazer, mas quero incluir validações de CNPJ, I.E. e outras, para isso terei que usar libs externas(algumas que eu mesmo estou desenvolvendo). Mas isso é futuro.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira 

Sobre as validações acredito que deva ser opcional ou tratado de forma diferente do que temos hoje, pois hoje tenho clientes com movimentação considerável e o arquivo demora um certo tempo parar ser gerado, se a cada problema ele der um exception ao invés de listar os problemas após gerar o arquivo (o que acontece hoje com campos obrigatórios) o processo fica moroso.

Abraços

**Comment by samuelrochaoliveira** [comment]
@marcosgerene as validações serão opcionais, sobre a lista de erros já temos esse método. Fiz o commit hoje mais cedo.

**Comment by samuelrochaoliveira** [comment]
Pacote NUGET publicado em https://www.nuget.org/packages/SPEDBr.NET/

**Comment by marcosgerene** [comment]
@samuelrochaoliveira 

O Nuget aparentemente está bem desatualizado, hoje eu compilo e referencio a dll compilada.

Existe alguma previsão de atualização do nuget?

**Comment by samuelrochaoliveira** [comment]
Fala @marcosgerene, tudo em paz?

Vou fazer a atualização desse pacote até o final de 2019. Após isso, vou passar a atualizar somente o projeto unificado FiscalBr.
