### ISSUE TITLE
Implementação de registros do Bloco C do sped Contribuições

### ISSUE THREAD

**Issue by victorcarlosgf** [AOPack/SPEDBr.NET#28]
Falta a implementação dos registros C395, C396, C400, C405, C481, C485, C489, C490, C491, C495 e C499 do bloco C do SPED Contribuições;

**Comment by douglashferreira** [comment]
C400, C405, C490 e C495 estão implementados sim, dos citados apenas os registros C395, C396, C481, C485, C489, C491 e C499 não estão implementados, pode ser que você ache em outros blocos mais registros faltando, a maioria é implementado conforme a necessidade que cada um teve.
Caso você precise com uma certa urgência, seguindo o padrão é bem fácil criar eles e você pode enviar depois por um PR para caso mais alguém precise.

**Comment by samuelrochaoliveira** [comment]
Os registros citados pelo @victorcarlosgf pertencem à EFD Contribuições, no SPED Fiscal realmente estão implementados. Já aceitei o pull, mas ainda faltam alguns, logo irei providenciar.

**Comment by samuelrochaoliveira** [comment]
@douglashferreira o @victorcarlosgf faz parte da equipe de desenvolvedores da Microplan, um dos patrocinadores do projeto. Face ao patrocínio temos a execução de "actions on-demand" quando existe a necessidade de incluir mais informações na lib.

**Comment by douglashferreira** [comment]
Entendi, eu havia implementado aqui e na correria acabei esquecendo de subir, mandei uma PR com as alterações.
