### ISSUE TITLE
Novo repositorio

### ISSUE THREAD

**Issue by gui-abrantes** [AOPack/SPEDBr.NET#45]
Olá Bom dia,

No readme deste repositório tem um aviso importante que a partir do 30/06/2018 este repositório deixará de ser atualizado.
Gostaria de saber qual repositório posso usar (novo ou este), caso desejasse ajudar com alguma contribuição ou utilizar mesmo a biblioteca de vocês.

Grato,
Guilherme

**Comment by samuelrochaoliveira** [comment]
Fala @gui-abrantes, tudo na paz?

Bom, essa data já foi protelada uma vez, minha intenção é completar a lib com as declarações restantes do projeto SPED e só fazer atualizações no layout quando necessário. Sem nenhuma grande mudança, ou nova implementação de funcionalidade. Tudo isso ocorrerá na nova lib que é NET STANDARD, pois essa daqui é NET FRAMEWORK.

Você pode usar este repositório daqui mesmo, no outro repositório ainda faltam alguns ajustes.

Para contribuir basta fazer um PR que irei analisar e aprovo se estiver ok.

*PS: Pode ser que a data seja adiada novamente, não sei quanto tempo irei levar para implementar todos os layouts do ECF, ECD e completar o SPED ICMS/IPI e EFD Contribuições, pois a maioria dos registros comuns já foram implementados mas todo o layout não, ou seja, o que atende a necessidade da maioria já foi feito, agora falta completar 100%.

Abraços.
