### ISSUE TITLE
Dúvida DIMOB

### ISSUE THREAD

**Issue by leandrossantos** [AOPack/SPEDBr.NET#47]
@samuelrochaoliveira parabéns pelo projeto primeiramente.

Gostaria de saber como gerar arquivo DIMOB para empresas de loteamento, estou com 2 clientes que são loteamento e estão precisando gerar o DIMOB e não estou conseguindo achar uma documentação clara para a geração do arquivo e o aplicativo da DIMOB da receita não abre na minha máquina também para ajudar mais ainda :(

Tem como você me dar uma luz ai?
Um pequeno exemplo em C# de quais classes tenho que alimentar e o que tenho que alimentar já me ajuda.

**Comment by samuelrochaoliveira** [comment]
Fala @leandrossantos, acordou cedo hein rapaz? kk

**Comment by leandrossantos** [comment]
@samuelrochaoliveira nem me fale, tirei apenas um cochilo essa noite, se muito uma 2 horas.

Tenho essa peleja ai do DIMOB para fazer, com 3 loteamentos e estou preciso de uma luz de onde começar e o que precisa ser informado para o seu componente para gerar.

Se você tiver um arquivo de DIMOB gerado ai para me mandar para eu dar uma olhada nele de como é gerado também vai me ajudar para eu entender como ele é.

Estou perdido pois nem o programa do DIMOB do governo abre na minha máquina.

**Comment by samuelrochaoliveira** [comment]
@leandrossantos, o primeiro passo é ter as informações do contrato, valor, data, cpf ou cnpj do comprador, nome do comprador, endereço, se é imóvel rural ou urbano, etc, a partir disto é só ir montando os registros, nada complexo, a biblioteca cuida de toda geração, fica tranquilo, ela gera certinho.

Tem uma software house aqui na minha cidade que usa ela e nunca reclamaram. O arquivo eu não tenho, e outra que é bem complicado ceder um arquivo pronto por conta das informações sensíveis da empresa e dos clientes. Mas se precisar de ajuda é só falar que no que eu puder lhe ajudo.

PS: Desinstala o programa e tenta instalar *executando como administrador*, usa o instalador deste link [aqui](http://idg.receita.fazenda.gov.br/orientacao/tributaria/declaracoes-e-demonstrativos/dimob-declaracao-de-informacoes-s-atividades-imobiliarias/programa-gerador-da-dimob-pgd).

**Comment by leandrossantos** [comment]
@samuelrochaoliveira vou tentar aqui pra ver se consigo gerar, as informações eu tenho pois eu que sou o programador do sistema que eles usam.

Só o programa do DIMOB mesmo que não vai de forma alguma, já fiz isso e mesmo assim não abre.

**Comment by samuelrochaoliveira** [comment]
Estranho... cria uma máquina virtual e bola pra frente.

**Comment by leandrossantos** [comment]
@samuelrochaoliveira ai também é problema, estou com Windows 10 Home Single Language, ai não deixa habilitar o Hyper-V, será que consigo criar uma maquina virtual no VirtualBox ou VMWare ??

**Comment by samuelrochaoliveira** [comment]
Acredito que com o **VirtualBox** sim. Desconheço o **VMWare**.

**Comment by leandrossantos** [comment]
@samuelrochaoliveira  um dúvida, esse codigo do municipio, é o codigo SIAFI ??  Porque o IBGE que usamos na NFe por exemplo não é

**Comment by samuelrochaoliveira** [comment]
O código do município é de uma tabela antiga que alguns sistemas da RFB usam, não era padrão IBGE. Esse código se encontra dentro do programa gerador da DIMOB, teria que consultar para saber. Qual o município que vc precisa?
Mas pesquisa por anexo A da DIMOB no Google e veja se consegue a tabela.

**Comment by samuelrochaoliveira** [comment]
Eu não conhecia por essa nomenclatura, sim é o SIAFI. Pesquisei agora e achei a tabela.

**Comment by leandrossantos** [comment]
@samuelrochaoliveira ao abrir o DIMOB aqui estou tendo o erro da imagem em anexo, já procurei na internet e não nada a respeito disso.
![screenshot_4](https://user-images.githubusercontent.com/6373944/36690943-315f01dc-1b0a-11e8-945b-1bfcadf43d70.png)

**Comment by samuelrochaoliveira** [comment]
Qual sua versão do Java? Abre o cmd e digita "java -version".

**Comment by samuelrochaoliveira** [comment]
A próxima vez que for instalar usa o modo de compatibilidade. O programa da DIMOB não funcionar na sua máquina é muito estranho. Instalei na minha Windows 10 em casa para testar, agora na hora do almoço, e funcionou, mas a minha é versão PRO.

**Comment by samuelrochaoliveira** [comment]
Tentou rodar pela VM do VirtualBox?

**Comment by samuelrochaoliveira** [comment]
@leandrossantos tem Skype? Me add, samueltcskp, para conversarmos melhor. Aqui já está ficando extenso. kk

**Comment by samuelrochaoliveira** [comment]
E aí @leandrossantos, conseguiu?

**Comment by leandrossantos** [comment]
Opa @samuelrochaoliveira, estou mexendo aqui, hoje a noite vai ser curta, rsrs 

Amanhã cedinho tenho que encaminhar para os contadores de 3 loteamentos.

**Comment by samuelrochaoliveira** [comment]
Se precisar de ajuda dá o grito no Skype. o/

**Comment by leandrossantos** [comment]
@samuelrochaoliveira bom dia, rapaz, com sua ajuda consegui sim. só estou com uma dúvida, no arquivo gerado esta ficando com uma linha embranco apos cada linha esta certo isso?

**Comment by samuelrochaoliveira** [comment]
Após cada linha de info está assim?
![dimob_erro_geracao](https://user-images.githubusercontent.com/15462690/36792608-bfa0d14e-1c79-11e8-9165-0285b93b09a2.PNG)

**Comment by leandrossantos** [comment]
Queira aqui deixar o meu agradecimento ao amigo @samuelrochaoliveira pela ajuda na geração do DIMOB.

Sua ajuda foi espetacular, Deus te Abençoe grande meu amigo.

**Comment by samuelrochaoliveira** [comment]
De nada @leandrossantos. Sucesso. o/

Abraços.

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
