### ISSUE TITLE
Sped ICMS IPI Registro H010 Campo CodCta

### ISSUE THREAD

**Issue by gsysteminformaticarp** [AOPack/SPEDBr.NET#52]
Olá estou tendo 1 problema com o Bloco H Registro H010 onde o campo 10 (CodCta) não esta retornando preenchido, no método escrever campos.

**Comment by marcosgerene** [comment]
Seu problema foi corrigido neste pull: https://github.com/AOPack/SPEDBr.NET/pull/49.

Por favor, atualize seu fonte.

**Comment by samuelrochaoliveira** [comment]
Olá @gsysteminformaticarp o amigo @marcosgerene procedeu com esta correção. Obrigado pela rápida resposta @marcosgerene o/

**Comment by gsysteminformaticarp** [comment]
@samuelrochaoliveira  @marcosgerene  Muito Obrigado Atualizei e problema resolvido
