### ISSUE TITLE
Mapear SpedFiscalFile com Registros Pai e Filhos p/ Futura Leitura

### ISSUE THREAD

**Issue by osamueloliveira** [AOPack/SPEDBr.NET#56]
Implementar registros com ocorrência 1, 1 : 1, 1 : N e V na classe [SpedFiscalFile ](https://github.com/AOPack/SPEDBr.NET/blob/master/SpedBr/SpedBr.SpedFiscal/SpedFiscalFile.cs)para leitura do arquivo SPED Fiscal.

Info: http://sped.rfb.gov.br/estatico/0D/2DC4C346EDFCDFAFA26C391C7398D060594B50/GUIA%20PR%c3%81TICO%20DA%20EFD%20-%20Vers%c3%a3o%202.0.22.pdf

**Comment by marcosgerene** [comment]
Vamos mapear sempre dentro do pai ne?

Ex:
SpedFiscal => Bloco0, BlocoC, BlocoD....

Bloco0 => Registro0000, Registro0100...

Registro0150 =>0175...

Correto?

**Comment by marcosgerene** [comment]
@samuelrochaoliveira  vou fazer todo o mapeamento do bloco 0 no pull https://github.com/AOPack/SPEDBr.NET/pull/57, e a cada bloco mando um pull novo pra gente ir acertando as coisas, qualquer inconsistência comenta no código mesmo, assim que eu "terminar o pull" te aviso pra ir aceitando, abraço

**Comment by samuelrochaoliveira** [comment]
Obrigado. o/

**Comment by leandrossantos** [comment]
@samuelrochaoliveira  e @marcosgerene  me tirem uma dúvida, com isso que vocês estão fazendo eu vou conseguir carregar um arquivo SPED gerado por uma ECF e com os dados dele importado adicionar as outras informações referentes ao restante do ERP, notas de entrada e notas de saída por exemplo?

**Comment by marcosgerene** [comment]
@leandrossantos sim, o componente vai preencher os objetos que vierem no arquivo importado e você pode manipular os objetos, acrescentar ou remover coisas, etc.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira com o pull #58 terminei o mapeamento dos filhos, mas boa parte do bloco D, algo em torno de 70% dele não está mapeado, vou abrir outra issue aqui para terminar de mapear ele.

**Comment by osamueloliveira** [comment]
Movida para o novo repositório https://github.com/osamueloliveira/FiscalBr.NET/issues/17
