### ISSUE TITLE
[SpedFiscal] Mapear registros restantes do bloco D

### ISSUE THREAD

**Issue by marcosgerene** [AOPack/SPEDBr.NET#59]
Na issue #56 notei que existiam registros ainda não mapeados no Sped Fiscal. Alguns do bloco K eu fiz já nos pulls #57 e #58, mas no bloco D o volume é muito maior, diria que algo em torno de 70% do bloco D ou até mais ainda tem que ser mapeado, então "quebrei" em 2 issues para não misturar os jobs.

**Comment by marcosgerene** [comment]
https://github.com/AOPack/SPEDBr.NET/pull/51

**Comment by osamueloliveira** [comment]
Movido para o novo repositório https://github.com/osamueloliveira/FiscalBr.NET/issues/18.
