### ISSUE TITLE
Banco de Dados ou XML direto?

### ISSUE THREAD

**Issue by marcosmarchiore** [AOPack/SPEDBr.NET#65]
Olá pessoal, estou implementando aqui o SPED, andei lendo algumas informações e observei que há pessoas que optam por guardar as informações em tabelas, a minha duvida aqui e a seguinte, pelo que li, acredito que lendo os XMLs tanto de entrada como de saida eu tenho as informações que preciso para gerar o SPED, exceto o inventario e algumas coisas  que realmente tenha que ter um historico no banco de dados, estou na linha correta ou vocês tem alguma sugestão para que eu possa utilizar a SPEDBr.NET com leitura do xmls e gerando os devidos arquivos.
Resumindo a minha ideia e ler os XMLs de entrada e saida e gerar os arquivos utilizando o SPEDBr.NET, guardando exclusivamente os XMLs, sem criar tabelas especificas.
Oque vocês acham, algum problema que não estou vendo ou sugestão, Obrigado a todos.

**Comment by danielgamajpa** [comment]
@marcosmarchiore, Recomendo que seja através de tabelas, devido a particularidades que essas NFe possuem.
Um exemplo no meu dia-a-dia é a questão no cadastro de notas de Fornecedores (C100) no "_Enfoque do Declarante_" (como consta em múltiplas partes da documentação).

Esta situação faz o seguinte: 
Caso e empresa que esteja gerando o SPED seja do regime de apuração Normal (CSTs do ICMS 00, 10, 60, etc) esteja recebendo XML de fornecedores do regime do Simples Nacional (CSOSN 101, 102, 201, 500, etc) este xml deve ser "convertido" para o "Enfoque do Declarante", ou seja, os CSTs dessas notas do simples, devem ser informados como a empresa do regime de apuração normal, já que o declarente do arquivo é do regime Normal.

> **Campo 10 (CST_ICMS)** – Preenchimento: o campo deverá ser preenchido com o código da Situação Tributária sob o enfoque do declarante.

Outra situação seria os códigos dos produtos que na documentação fala:

> A identificação do item (produto ou serviço) **deverá receber o código próprio do informante do arquivo em qualquer documento, lançamento efetuado ou arquivo informado** (significa que o código de produto deve ser o mesmo na emissão dos documentos fiscais, na entrada das mercadorias ou em qualquer outra informação prestada ao fisco)

Ou seja, o código do Fornecedor pode ser diferente do que é aplicativo na aplicação do cliente.

Então é isso.

**Comment by marcosmarchiore** [comment]
@danielgamajpa era esse o ponto de vista que eu precisava, perfeito, não há duvida que somente com os XMLs eu vá conseguir ter um resultado adequado, a parte do códigos dos produtos do cliente já acaba com a utilização dos XMLs, agora oque me chamou a atenção e a troca da informação da nota de entrada, os CSTs e CSOSNs, no ato de gerar o registro eu tenho que substituir as informações recebidas do XMLs para as adequadas para o regime do meu cliente ?

**Comment by danielgamajpa** [comment]
Exatamente. 
Também tem a questão inversa. Caso o cliente seja do regime do Simples Nacional, onde além das situações tributárias serem trocadas, as alíquotas e valores do ICMS serem de certa forma "diferenciados". Há situações também que a empresa não credita-se do ICMS e com isso a informação deva ir "zerada" , mesmo constando no XML do fornecedor este dado. 

> IMPORTANTE: para documentos de entrada, os campos de valor de imposto, base de cálculo e alíquota só devem ser informados se o adquirente tiver direito à apropriação do crédito (enfoque do declarante).

Outra situação são notas cujo fornecedor irá emitir com o CFOP 5102/6102, e o cliente dê entrada como "uso e consumo" CFOP 1556/2556.

Quando se fala do SPED Contribuições já são outras informações que também não constam no XML do fornecedor (que esteja emitindo NF de venda), como por exemplo o CST do Pis/Cofins que XML possa vir como 01, 04, 06, 07, etc, e quando for cadastra-los como notas de entrada ter que alterar para 50, 71, 72 73, etc).

Outras informações que não constam no XML é o "Plano de Contas" que no EFD Contribuições se tornou obrigatório.

Estes são alguns exemplos de informações que fazem com que a melhor escolha seja de fato a gravação das informações em tabela antes da geração do arquivo.
