### ISSUE TITLE
BLOCO E Registro E113 Novo campo CHV_DOCe

### ISSUE THREAD

**Issue by marcosmarchiore** [AOPack/SPEDBr.NET#67]
Olá amigos, primeiramente parabéns pelo trabalho, na utilização da SPEDBr.NET observei em que no BLOCO E Registro  E113 esta faltando o campo CHV_DOCe 10 campo de acordo com Guia Prático EFD-ICMS/IPI – Versão 2.0.22.
Já implementei no meu aqui, mas e bom avisar OK.

**Comment by samuelrochaoliveira** [comment]
Obrigado por avisar @marcosmarchiore. A adição do novo campo foi feita no commit 8586d33162664a41665e1c953a7e5f2edec6a7d6. o/
