### ISSUE TITLE
Documentação spedbr

### ISSUE THREAD

**Issue by renatomateusx** [AOPack/SPEDBr.NET#68]
Pessoal, bom dia

Tem alguma documentação para seguir e gerar o arquivo efd com o spedbr?
Obrigado e Abraço.

**Comment by eduprog** [comment]
https://www.google.com.br/url?sa=t&source=web&rct=j&url=http://sped.rfb.gov.br/estatico/20/4E78FBAD67086070031C828FDAEF8F5DD19BD0/Guia_Pratico_EFD_Contribuicoes_Versao_1_22.pdf&ved=2ahUKEwj1-JWZ0I_cAhUJlZAKHX3jCCoQFjAAegQIBRAB&usg=AOvVaw04m9LNxmO-wvaq2ooyXBXn

**Comment by osamueloliveira** [comment]
Fala @renatomateusx beleza?

Na página do novo repositório você encontrará alguns exemplos, hoje ainda estarei incluindo novas informações lá.

Para acessar o novo repositório, [clique aqui](https://github.com/osamueloliveira/FiscalBr.NET).

Vida longa e próspera. 🖖
