### ISSUE TITLE
[Sped Contábil - ECF] Estado atual do projeto

### ISSUE THREAD

**Issue by marcosgerene** [AOPack/SPEDBr.NET#70]
Bom dia,

Vi que já existe classes criadas para o SPED Contábil (ECF), qual o estado atual do projeto? tem alguém já usando em produção?

**Comment by samuelrochaoliveira** [comment]
Não. Implementei a pouco tempo e nessa semana irei colocar em produção para um cliente. Ainda estou codificando a captação de dados para preencher o arquivo.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira 

Vi um arquivo que veio pra análise aqui e usava-se muito o bloco I (ainda não sei o significado dos blocos, sequer comecei o  estudo sobre o projeto).

Vi que o bloco citado não está implementado, o mapeamento segue a mesma lógica dos outros arquivos (mapeei bastante coisa do fisca e contribuições quando comecei).

PS: Não entendi a diferença entre o ECF e o ECD.

**Comment by samuelrochaoliveira** [comment]
@marcosgerene 

> Vi um arquivo que veio pra análise aqui e usava-se muito o bloco I (ainda não sei o significado dos blocos, sequer comecei o estudo sobre o projeto).

![image](https://user-images.githubusercontent.com/15462690/43096859-bd2faf3c-8e90-11e8-9385-b6010ef5dd04.png)

> Vi que o bloco citado não está implementado, o mapeamento segue a mesma lógica dos outros arquivos (mapeei bastante coisa do fisca e contribuições quando comecei).

![image](https://user-images.githubusercontent.com/15462690/43096971-09f1fbc2-8e91-11e8-9124-a6507ec85b36.png)

**[RESPOSTA DA 1º E DA 2º CITAÇÃO]**
Na ECD o Bloco I é a parte do Plano de Contas e na ECF o Bloco C corresponde a essa parte. A diferença é que os dados podem ser importados num arquivo da ECF já existente e você pode optar em deixar o Validador alterar os valores de saldos e demais cálculos necessários. Ou você pode criar a ECF do zero e o Bloco I não irá aparecer, somente o Bloco C.

> PS: Não entendi a diferença entre o ECF e o ECD.

ECF = Escrituração Contábil Fiscal (é uma espécie de complemento da ECD (SPED Contábil), para informar distribuições de lucros entre os sócios, cálculos de impostos federais dentre outras informações fiscais).

ECD = Escrituração Contábil Digital ou SPED Contábil (é a declaração eletrônica que substitui os famosos livros, caixa, razão, diário, balancete, DRE, DMPL, etc). A contabilidade e todos os seus lançamentos em forma de arquivo magnético.

Abraços.

**Comment by marcosgerene** [comment]
Acredito que sanou minhas dúvidas, obrigado
