### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by cardosodearaujo** [AOPack/SPEDBr.NET#72]
Boa tarde!
Estou a procura de um projeto open source que me ajude a gerar o Sped Contribuições de maneira mais rápida pois tenho pouco tempo para entregar para um cliente.
Gostaria de saber se o projeto de vocês já está em pleno funcionamento? Se não gostaria de saber o que ainda falta? E como posso contribuir?

**Comment by marcosgerene** [comment]
Utilizo o Sped Fiscal em produção para bastante clientes a um bom tempo...

Contribuições acho que está ok tbm.

**Comment by cardosodearaujo** [comment]
Show de bola! Dei uma olhada aqui e aparentemente está tudo OK.
Muito obrigado!

**Comment by lickoski** [comment]
Bom dia, esta biblioteca oferece suporte para leitura de um arquivo do SPED Fiscal já existente ?

**Comment by samuelrochaoliveira** [comment]
@lickoski ainda não mas, está no roadmap para o mês que vem.

**Comment by marcosgerene** [comment]
@lickoski eu e o Samuel começamos a ver isso, mas, do meu lado, os outros projetos com urgencia acabaram sufocando o tempo disponível, e o cliente que estava buscando isso acabou não fechando o projeto, então acabei não mexendo mais.

Mas é bom saber que o @samuelrochaoliveira está pensando em continuar, excelente!
