### ISSUE TITLE
BlocoB  Não esta saindo no Nuget

### ISSUE THREAD

**Issue by fabiociaf** [AOPack/SPEDBr.NET#74]
Ola, 
Parece que o Nuget nao esta atualizado com o projeto daqui.
Gostaria que atualizasse la para usar a biblioteca corretamente. 

Pois lá o bloco B nao esta parametrizado. 

Obrigado.

**Comment by samuelrochaoliveira** [comment]
Fala @fabiociaf tudo blz?

Farei todas as atualizações paradas até o dia 15/04. A partir de agora farei sprints quinzenais para atualizar a lib. Há muitos detalhes ainda para serem implementados.

Abraços.

**Comment by fabiociaf** [comment]
Obrigado pelo retorno!

**Comment by osamueloliveira** [comment]
Fala @fabiociaf beleza?

Cara, acessa o novo repositório que já está prontinho lá todos os pacotes Nuget.

Para acessar, [clique aqui](https://github.com/osamueloliveira/FiscalBr.NET).

Vida longa e próspera. 🖖
