### ISSUE TITLE
bloco b001

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [AOPack/SPEDBr.NET#76]
Bom dia,
Em quais situações eu devo informar o indicador do movimento do bloco B001  como 1 ou 0 ?
Estou com essa duvida.

**Comment by douglashferreira** [comment]
Bom dia Edson, o Bloco B é para informações referentes a ISS.
Em todos meus arquivos eu abro o Bloco B com 1 e coloco o B990 com a quantidade 2.
Nunca tive problemas em informar assim(todos meus clientes são lojas de varejo nada com serviço)

**Comment by samuelrochaoliveira** [comment]
@EdsonRodrigoBA com exceção das empresas localizadas no DF todas as demais UFs devem informar o indicador 1 (SEM informações).

Acredito que o DF seja a UF de teste desse bloco e em breve todas as demais UFs estarão obrigadas, mas até lá, só abra e feche o registro sem nenhuma informação.

Abraços.

**Comment by EdsonRodrigoBA** [comment]
Obrigado, pelo feedback, entendi.
Parabéns pela biblioteca muito útil e simples de utilizar.
Implementei o Sintegra agora estou no mundo do speed.

**Comment by samuelrochaoliveira** [comment]
Caso tenha mais dúvidas não hesite em compartilhar. o/

Abraços.
