### ISSUE TITLE
duvidas bloco C

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [AOPack/SPEDBr.NET#77]
Para cada registri C100 eu devo ter o seu registro C170 e C190 ?
Exemplo: Supondo que tenho um Cupom com 5 items e uma NF com 3 itens:
No bloco C ficaria:
C100: CUPOM1
C170: ITEM1
C170: ITEM2
C170: ITEM3
C170: ITEM4
C170: ITEM5
C190: TOTAIS
C100: NF
C170: ITEM1
C170: ITEM2
C170: ITEM3
C170: ITEM4
C170: ITEM5
C190: TOTAIS

È isso mesmo ?

**Comment by samuelrochaoliveira** [comment]
Exato.

Mas lhe faço 2 ressalvas:

1 - Se o documento for de emissão própria, NFC-e ou NF-e por exemplo que a própria empresa emitiu a nota fiscal, não precisa informar o C170.

![image](https://user-images.githubusercontent.com/15462690/62778066-ab5e2000-ba85-11e9-9cbf-3b5d4d4ddacf.png)
Exceção 2 que consta na página 55 do Manual da EFD versão 3.0.1

![image](https://user-images.githubusercontent.com/15462690/62778122-e2343600-ba85-11e9-8a31-bd607f305cac.png)
Exceção 9 que consta na página 56 do Manual da EFD versão 3.0.1

2 - Por questão estética mesmo, ordene os documentos por data. :)

Abraços.

**Comment by EdsonRodrigoBA** [comment]
Hum.. Entendi
Qual manual é esse que você esta utilizando.?
Poderia me enviar?
Entao entendendo
![Uploading image.png…]()

**Comment by EdsonRodrigoBA** [comment]
Este registro deve ser gerado para cada documento fiscal código 01, 1B, 04, 55 e 65 (NFC-e), registrando a entrada
ou saída de produtos ou outras situações que envolvam a emissão dos documentos fiscais mencionados,
representativos de receitas auferidas, tributadas ou não pelo PIS/Pasep ou pela Cofins, bem como de operações de
aquisições e/ou devoluções com direito a crédito da não cumulatividade.
Não devem ser informados documentos fiscais que não se refiram a operações geradoras de receitas ou de créditos
de PIS/Pasep e de Cofins.
Para cada registro C100, obrigatoriamente deve ser apresentado, pelo menos, um registro C170, exceto em relação
aos documentos fiscais referentes à nota fiscal cancelada (código “02” ou “03”), Nota Fiscal Eletrônica (NF-e)
denegada (código “04”) ou numeração inutilizada (código “05”), os quais não devem ser escriturados os registros
filhos de C100.
Não podem ser informados, para um mesmo documento fiscal, dois ou mais registros com a mesma combinação de
valores dos campos formadores da chave do registro. A chave deste registro é:
• para documentos com campo “IND_EMIT” igual a “1” (um) – emissão por terceiros: campo IND_OPER, campo
IND_EMIT, campo COD_PART, campo COD_MOD, campo COD_SIT, campo SER e campo NUM_DOC;
• para documentos com campo “IND_EMIT” igual “0” (zero) – emissão própria: campo IND_OPER, campo
IND_EMIT, campo COD_MOD, campo COD_SIT, campo SER e campo NUM_DOC.
No manual que tenho diz isso.

**Comment by samuelrochaoliveira** [comment]
Manual da EFD Fiscal (ICMS/IPI):
[http://sped.rfb.gov.br/estatico/AE/B0DEF8D93F24CB4EEFE8AD1443A14E7E8F4319/GUIA%20PR%c3%81TICO%20EFD%20ICMS%20IPI%20-%20Vers%c3%a3o%203.01.pdf](http://sped.rfb.gov.br/estatico/AE/B0DEF8D93F24CB4EEFE8AD1443A14E7E8F4319/GUIA%20PR%c3%81TICO%20EFD%20ICMS%20IPI%20-%20Vers%c3%a3o%203.01.pdf)

Manual da EFD Contribuições (PIS/Cofins):
[http://sped.rfb.gov.br/estatico/20/6E34811D4F98083196E2A09880F048189788FC/Guia_Pratico_EFD_Contribuicoes_Versao_1_31%20-%2029_04_2019.pdf](http://sped.rfb.gov.br/estatico/20/6E34811D4F98083196E2A09880F048189788FC/Guia_Pratico_EFD_Contribuicoes_Versao_1_31%20-%2029_04_2019.pdf)

**Comment by EdsonRodrigoBA** [comment]
Agora fiquei na duvida:
Para cada registro C100, obrigatoriamente deve ser apresentado, pelo menos, um registro C170, exceto em relação
aos documentos fiscais referentes à nota fiscal cancelada (código “02” ou “03”), Nota Fiscal Eletrônica (NF-e)
Porque no Manual que peguei diz isso.

**Comment by samuelrochaoliveira** [comment]
Esses manuais que eu coloquei os links são os mais atualizados.

Mas tenha em mente que existem duas situações:

**Primeira**

Notas de saídas (vendas na sua maioria) não precisa informar os itens pois a SEFAZ já sabe os itens presentes nessa nota.

**Segunda**

Notas de entrada, se a empresa compra e tem direito a crédito ou não de imposto, deve informar de qualquer maneira.

Cada manual é de uma obrigação, você está desenvolvendo SPED para qual cenário? Fiscal (ICMS) ou Contribuições (PIS/Cofins)?

**Comment by EdsonRodrigoBA** [comment]
Estou desenvolvendo para empresas do simples nacional.
Qual manual devo utilizar ?

**Comment by samuelrochaoliveira** [comment]
Dependendo do Estado empresas do Simples Nacional **NÃO** são obrigadas a transmitir EFD.

Consulte se a empresa está obrigada a EFD nesse link:
[https://www.sped.fazenda.gov.br/spedfiscalserver/ConsultaContribuinte/Default.aspx](https://www.sped.fazenda.gov.br/spedfiscalserver/ConsultaContribuinte/Default.aspx)

Dependendo do resultado da consulta confirme com o(a) contador(a) quais registros são obrigatórios para a empresa.
