### ISSUE TITLE
Esta em conformidade com o bloco k ?

### ISSUE THREAD

**Issue by johnpaini** [AOPack/SPEDBr.NET#78]
Boa tarde o projeto atende as exigencias de bloco k, ou tem alguma implementação futura sobre esse aspecto?

**Comment by osamueloliveira** [comment]
Fala @johnpaini e @marcosgerene beleza?

O novo repositório já está em produção, para acessar [clique aqui](https://github.com/osamueloliveira/FiscalBr.NET).

O Bloco K está 99% concluído, apenas irei fazer uma revisão do layout nesses próximos dias.

Vida longa e próspera. 🖖
