### ISSUE TITLE
Qual projeto usar/contribuir?

### ISSUE THREAD

**Issue by gui-abrantes** [AOPack/SPEDBr.NET#79]
Olá boa noite,

Vi que está em desenvolvimento um outro projeto:
https://github.com/osamueloliveira/FiscalBr.NET

Qual projeto devo utilizar, qual a diferença entre eles?

**Comment by osamueloliveira** [comment]
Fala @gui-abrantes tudo na paz?

Atualmente os 2 projetos estão bem parecidos. Vou manter esse projeto ativo até o final de 2020. E após isso o principal será o FiscalBr.

**Comment by osamueloliveira** [comment]
Fala @gui-abrantes beleza?

Cara, usa o projeto [FiscalBr.NET](https://github.com/osamueloliveira/FiscalBr.NET), ele que está sendo atualizado e mantido a partir de 2020.
