### ISSUE TITLE
GERACAO DO BLOCO X

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [AOPack/SPEDBr.NET#80]
Acredito que minha pergunta não tenha haver com esse projeto mais,
Qual biblioteca vocês utilizam para gerar o bloco X no formato XML ?, estou com essa necessidade de implementação.

**Comment by osamueloliveira** [comment]
Fala @EdsonRodrigoBA beleza?

Cara... Fazia muito tempo que eu não ouvia falar do Bloco X, acredito que hoje seja específico somente para o estado de Santa Catarina. Mas, respondendo a sua pergunta. Não conheço ninguém que tenha clientes em SC, e a lib do SPEDBr atende tão somente os arquivo do Projeto SPED.

Posta essa issue lá no projeto do DFe.NET, talvez tenha alguém que possa te ajudar.

Abraços.

**Comment by Julianoze** [comment]
Edson, 
posso te auxiliar!

**Comment by EdsonRodrigoBA** [comment]
bom dia, Juliano, você tem alguma biblioteca para geração desse arquivos?

**Comment by Julianoze** [comment]
Edson, 
existe uma aqui no Github
mas ela não possui a geração de estoque

Eu tenho somente a que implementei para empresa
Mas posso te auxiliar, ou implementar a presente aqui

https://github.com/Bertoncini/BlocoX/pull/1

Lembrando que ela não possui estoque, o que é necessário
Para qual CNAE você irá desenvolver?

**Comment by EdsonRodrigoBA** [comment]
Entendi, preciso da parte de redução Z, 
o CNAE é: Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal .

**Comment by Julianoze** [comment]
Este código acima vai te ajudar
mas ele está com diversos problemas, que você irá encontrar ao longo do caminho

Eu te mandei um email, se puder verificar
te passo as orientações

**Comment by EdsonRodrigoBA** [comment]
Estou olhando, com essa biblioteca eu consigo montar o XML ?

**Comment by Julianoze** [comment]
Cara, consegue 
só que como te falei, eu dei uma analisada, 

no meu caso eu descobri após fazer a minha, só que ao usar 
terá um monte de problemas.

Me manda um email:
juliano_braz@hotmail.com

Pelo que vi seu CNAE já está obrigado, e vocês podem ter problemas com a geração do arquivo.
