### ISSUE TITLE
Organização Bloco C

### ISSUE THREAD

**Issue by douglashferreira** [AOPack/SPEDBr.NET#82]
Devido ao tamanho do bloco C eu acabei criando uma pasta e separei as partes em vários arquivos por _partial class_ no meu projeto interno, se acharem interessante eu posso fazer aqui também acaba ficando mais fácil editar e achar as coisas no meio,  já esta com **5045** linhas o bloco C
![image](https://user-images.githubusercontent.com/17594937/71596033-c1e04300-2b1c-11ea-9932-454961d4c2d9.png)
Os Registros 300, 600 e 700 não uso por isso não dividi.

**Comment by marcosgerene** [comment]
Aproveita e pega esse PR então

https://github.com/AOPack/SPEDBr.NET/pull/83

**Comment by douglashferreira** [comment]
Show! 
Vou pegar pra fazer isso fim de semana, esse bloco está muito grande fica difícil achar as coisas no meio, os demais eu nem cheguei a ver porque não mecho muito, mas vou ver eles também.

> Aproveita e pega esse PR então
> 
> #83
