### ISSUE TITLE
Duvida entre Repositórios

### ISSUE THREAD

**Issue by adrbarros** [AOPack/SPEDBr.NET#84]
Bom existem 2 Repositórios, este repositório seria descontinuado em 31/12/2019, realmente procede?
repositório atual: https://github.com/osamueloliveira/FiscalBr.NET.

O que me dizem?

**Comment by osamueloliveira** [comment]
Fala @adrbarros beleza?

Cara, usa o projeto [FiscalBr.NET](https://github.com/osamueloliveira/FiscalBr.NET), ele que será mantido e atualizado de 2020 para frente.
