### ISSUE TITLE
Por Favor uma Ajudinha

### ISSUE THREAD

**Issue by dionathanbatista** [AOPack/SPEDBr.NET#87]
Boa Noite.
Sou novo por aqui, sou novo em sped.
Preciso gerar um sped de uma empresa.
Tenho todas as informações necessárias em um banco de dados, gostaria de gerar o sped pela biblioteca mas não sei nem por onde começar.
Alguém poderia me dar uma ajuda.
Onde começo, onde gero o arquivo, como proceder?

achei esse exemplo porem como transformá-lo no arquivo?

// SPED Fiscal
                var reg0000 = new SpedBr.SpedFiscal.Bloco0.Registro0000();
                var reg0001 = new SpedBr.SpedFiscal.Bloco0.Registro0001();
                reg0000.CodVer = 1;
                reg0000.CodFin = IndCodFinalidadeArquivo.RemessaArquivoOriginal;
                reg0000.DtIni = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
                reg0000.DtFin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ObterUltimoDiaMesAtual();
                reg0000.Nome = "GDM INFORMATICA LTDA";
                reg0000.Cnpj = "26.061.041/0001-81";
                reg0000.Uf = "MT";
Socorro!

**Comment by osamueloliveira** [comment]
Fala @dionathanbatista, tudo bom?

Dá uma olhada nos testes:
https://github.com/AOPack/SPEDBr.NET/blob/master/SpedBr/SpedBr.Tests/SpedFiscalUnitTest.cs

A cada registro criado chame o método que escreve as linhas depois é só salvar as linhas em um novo arquivo.

**Comment by dionathanbatista** [comment]
> Fala @dionathanbatista, tudo bom?
> 
> Dá uma olhada nos testes:
> https://github.com/AOPack/SPEDBr.NET/blob/master/SpedBr/SpedBr.Tests/SpedFiscalUnitTest.cs
> 
> A cada registro criado chame o método que escreve as linhas depois é só salvar as linhas em um arquivo.
> 
> Na linha 361 do arquivo https://github.com/AOPack/SPEDBr.NET/blob/master/SpedBr/SpedBr.AppTeste/ucSintegra.cs é possível ver como é gerado o arquivo.
> 
> Qualquer dúvida é só postar aqui.

Bom Dia.
Tudo ótimo e vc?
Vou tentar fazer hj qualquer duvida volto aqui

**Comment by osamueloliveira** [comment]
Fala @dionathanbatista tudo em paz?

Conseguiu consumir a lib?

Qualquer dúvida posta aí.

**Comment by dionathanbatista** [comment]
> Fala @dionathanbatista tudo em paz?
> 
> Conseguiu consumir a lib?
> 
> Qualquer dúvida posta aí.

Boa noite!
Estou mexendo ainda rsrs algumas coisas deram certo
Assim que terminar eu encerro pois ainda haverá algumas duvidas
desde já agradeço a todos

**Comment by osamueloliveira** [comment]
Fala @dionathanbatista beleza?

Cara, usa o projeto [FiscalBr.NET](https://github.com/osamueloliveira/FiscalBr.NET) de agora pra frente, ele que será mantido e atualizado.

Vida longa e próspera. 🖖
